class TaskAlreadyRunningException implements Exception {
  const TaskAlreadyRunningException();
}
